blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/Dmoore628/PersonalAssistant/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/Dmoore628/PersonalAssistant/tree/main/docs
    about: Browse the project documentation
  - name: 🔒 Security Issues
    url: https://github.com/Dmoore628/PersonalAssistant/security/advisories
    about: Report security vulnerabilities privately